### ISSUE TITLE
About model weights download

### ISSUE THREAD

**Issue by Shann-Dong** [Hongje/OTVM#10]
Thank you for your project. I am interested in testing it on the VideoMatting108 dataset as well as on my custom dataset. However, it seems there is an issue with the downloaded model weights. According to the README, I may have downloaded an HTML file from the wrong page. When I run `bash scripts/eval_s4.sh 0`, the following error occurs:
`_pickle.UnpicklingError: invalid load key, '\x0d'.`

Could you please advise on how to obtain the correct model weights such as s4_OTVM.pth?Thanks!

**Comment by Hongje** [comment]
Hi,

Thanks for your interest in our work. I have noticed that the download links in README are no longer valid. Please use the following Google Drive link to download the weights:

https://drive.google.com/drive/folders/1La53_oYZjhmcd2pfPPlnibLBPE12mc6b

Thanks

**Comment by Shann-Dong** [comment]
> Hi,
> 
> Thanks for your interest in our work. I have noticed that the download links in README are no longer valid. Please use the following Google Drive link to download the weights:
> 
> https://drive.google.com/drive/folders/1La53_oYZjhmcd2pfPPlnibLBPE12mc6b
> 
> Thanks

Thank you very much for your reply. I will give it another try!
